//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodoApp.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heli.
        /// </summary>
        public static string Heli {
            get {
                return ResourceManager.GetString("Heli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keel.
        /// </summary>
        public static string Keel {
            get {
                return ResourceManager.GetString("Keel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta.
        /// </summary>
        public static string Kustuta {
            get {
                return ResourceManager.GetString("Kustuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa.
        /// </summary>
        public static string Lisa {
            get {
                return ResourceManager.GetString("Lisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muuda.
        /// </summary>
        public static string Muuda {
            get {
                return ResourceManager.GetString("Muuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvesta.
        /// </summary>
        public static string Salvesta {
            get {
                return ResourceManager.GetString("Salvesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seaded.
        /// </summary>
        public static string Seaded {
            get {
                return ResourceManager.GetString("Seaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teema.
        /// </summary>
        public static string Teema {
            get {
                return ResourceManager.GetString("Teema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülesanded.
        /// </summary>
        public static string Ulesanded {
            get {
                return ResourceManager.GetString("Ulesanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valmis.
        /// </summary>
        public static string Valmis {
            get {
                return ResourceManager.GetString("Valmis", resourceCulture);
            }
        }
    }
}
